### ISSUE TITLE
关于cmpp connect 认证一直失败的问题

### ISSUE THREAD

**Issue by zackzhangkai** [a982338665/send_message#1]
你好，关于模拟器的配置，我现在自己实现客户端，我该用哪个spid/passwd来连接这个server??

[serv_cfg]
servip=127.0.0.1
servport=7891
ismg_id=001001
miscid=1234
sockettimeout=10

[client_cfg]
icpid=901234,61613,901236,901237,901238
pwd=1234,zhjy1234,1236,99999,1238
spid=901234,10657061602,09997,09998,09999
validip=127.0.0.1,127.0.0.1,127.0.0.1,192.168.0.3,192.168.0.4

**Comment by a982338665** [comment]
没太懂你什么意思

**Comment by a982338665** [comment]
最好是截图说明一下
